POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "member2",
    "name" :"Member 2",
    "password" : "12"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "member3",
    "name" :"Member 3",
    "password" : "12345"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "admin",
    "name": "root user",
    "password": "1234"
}