POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "My first blog",
    "author" :"Anna Morch",
    "url" : "http://localhost:3003",
    "likes":3
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "this is a test user blog",
    "author" :"Liana Maria",
    "url" : "http://localhost:3003",
    "userId" : "69d66724a135a663711d8baf"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "this is another blog for the user 'admin'",
    "author" :"admin",
    "url" : "http://localhost:3003",
    "userId" : "69d66724a135a663711d8baf"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "new blog with authentication for the user 'admin'",
    "author" :"admin",
    "url" : "http://localhost:3003",
    "userId" : "69d66724a135a663711d8baf"
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2OWQ4YjIzNGFhNWY2Mjk0MjYyNDI4ZDAiLCJpYXQiOjE3NzU5MTAwMzB9.eeUbPAHj35w8k7eMaRMdY4mNlhzsnCXw46lkUQ7Qb6M

{
    "title": "Token Verified Blog",
    "author": "The Admin",
    "url": "http://admin-site.com",
    "likes": 5
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2OWQ4YjIzNGFhNWY2Mjk0MjYyNDI4ZDAiLCJpYXQiOjE3NzU5MTAwMzB9.eeUbPAHj35w8k7eMaRMdY4mNlhzsnCXw46lkUQ7Qb6M

{
    "title": "Blog after adding tokenExtractor to middleware ",
    "author": "The Admin",
    "url": "http://admin-site.com",
    "likes": 5
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2OWQ4YjIzNGFhNWY2Mjk0MjYyNDI4ZDAiLCJpYXQiOjE3NzU5MTAwMzB9.eeUbPAHj35w8k7eMaRMdY4mNlhzsnCXw46lkUQ7Qb6M

{
    "title": "Blog To Delete",
    "author": "The Admin",
    "url": "http://admin-site.com",
    "likes": 5
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lbWJlcjMiLCJpZCI6IjY5ZGI2YWM1NzQwN2NlMjRkZTgyNTk0MiIsImlhdCI6MTc3NTk4NzQyNH0.bimLJJhIubtsphN_Y_38-hA2bolzjv7laetTTJvc7LM

{
    "title": "Blog To Delete",
    "author": "member3",
    "url": "http://member-site.com",
    "likes": 5
}