PuT http://localhost:3003/api/blogs/69b188c83743fdb143b22d1d
Content-Type: application/json

{
    "title" : "this is an update for the  blog",
    "author" :"Marta Scott",
    "url" : "http://localhost:3003",
    "likes" : 6
}
###
PuT http://localhost:3003/api/blogs/69c501953028f145fe9bc7d7
Content-Type: application/json

{
    "likes" : 17
}