POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Adam Balck",
    "number" :"12-33-187281"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Dan Abramov",
    "number" : "12-33-18989"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "",
    "number": "0877323"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Jack A",
    "number": ""
}

###
POST https://fullstackopenphonebook-3fa3.onrender.com/api/persons
Content-Type: application/json

{
    "name" : "Adam Balck",
    "number" :"12-33-187281"
}

###
GET https://fullstackopenphonebook-3fa3.onrender.com/